/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UploadScreenshot200
} from '../../model';


export const getUploadScreenshotResponseMock = (overrideResponse: Partial<Extract<UploadScreenshot200, object>> = {}): UploadScreenshot200 => ({key: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getUploadScreenshotMockHandler = (overrideResponse?: UploadScreenshot200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UploadScreenshot200> | UploadScreenshot200), options?: RequestHandlerOptions) => {
  return http.put('*/workspaces/:id/screenshots/:selectionId/:type', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadScreenshotResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetScreenshotMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/workspaces/:id/screenshots/:selectionId/:type', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getScreenshotsMock = () => [
  getUploadScreenshotMockHandler(),
  getGetScreenshotMockHandler()
]
