/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetScreenshot404,
  UploadScreenshot200,
  UploadScreenshot415
} from '../../model';





/**
 * @summary Upload a screenshot
 */
export type uploadScreenshotResponse200 = {
  data: UploadScreenshot200
  status: 200
}

export type uploadScreenshotResponse415 = {
  data: UploadScreenshot415
  status: 415
}

export type uploadScreenshotResponseSuccess = (uploadScreenshotResponse200) & {
  headers: Headers;
};
export type uploadScreenshotResponseError = (uploadScreenshotResponse415) & {
  headers: Headers;
};

export type uploadScreenshotResponse = (uploadScreenshotResponseSuccess | uploadScreenshotResponseError)

export const getUploadScreenshotUrl = (id: string,
    selectionId: string,
    type: 'full' | 'element',) => {




  return `/workspaces/${id}/screenshots/${selectionId}/${type}`
}

export const uploadScreenshot = async (id: string,
    selectionId: string,
    type: 'full' | 'element',
    uploadScreenshotBody: Blob, options?: RequestInit): Promise<uploadScreenshotResponse> => {

  const res = await fetch(getUploadScreenshotUrl(id,selectionId,type),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'image/png', ...options?.headers },
    body: JSON.stringify(
      uploadScreenshotBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadScreenshotResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadScreenshotResponse
}




export const getUploadScreenshotMutationOptions = <TError = UploadScreenshot415,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadScreenshot>>, TError,{id: string;selectionId: string;type: 'full' | 'element';data: Blob}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof uploadScreenshot>>, TError,{id: string;selectionId: string;type: 'full' | 'element';data: Blob}, TContext> => {

const mutationKey = ['uploadScreenshot'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadScreenshot>>, {id: string;selectionId: string;type: 'full' | 'element';data: Blob}> = (props) => {
          const {id,selectionId,type,data} = props ?? {};

          return  uploadScreenshot(id,selectionId,type,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadScreenshotMutationResult = NonNullable<Awaited<ReturnType<typeof uploadScreenshot>>>
    export type UploadScreenshotMutationBody = Blob
    export type UploadScreenshotMutationError = UploadScreenshot415

    /**
 * @summary Upload a screenshot
 */
export const useUploadScreenshot = <TError = UploadScreenshot415,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadScreenshot>>, TError,{id: string;selectionId: string;type: 'full' | 'element';data: Blob}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadScreenshot>>,
        TError,
        {id: string;selectionId: string;type: 'full' | 'element';data: Blob},
        TContext
      > => {
      return useMutation(getUploadScreenshotMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a screenshot
 */
export type getScreenshotResponse200 = {
  data: void
  status: 200
}

export type getScreenshotResponse404 = {
  data: GetScreenshot404
  status: 404
}

export type getScreenshotResponseSuccess = (getScreenshotResponse200) & {
  headers: Headers;
};
export type getScreenshotResponseError = (getScreenshotResponse404) & {
  headers: Headers;
};

export type getScreenshotResponse = (getScreenshotResponseSuccess | getScreenshotResponseError)

export const getGetScreenshotUrl = (id: string,
    selectionId: string,
    type: 'full' | 'element',) => {




  return `/workspaces/${id}/screenshots/${selectionId}/${type}`
}

export const getScreenshot = async (id: string,
    selectionId: string,
    type: 'full' | 'element', options?: RequestInit): Promise<getScreenshotResponse> => {

  const res = await fetch(getGetScreenshotUrl(id,selectionId,type),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getScreenshotResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getScreenshotResponse
}





export const getGetScreenshotQueryKey = (id: string,
    selectionId: string,
    type: 'full' | 'element',) => {
    return [
    `/workspaces/${id}/screenshots/${selectionId}/${type}`
    ] as const;
    }


export const getGetScreenshotQueryOptions = <TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScreenshotQueryKey(id,selectionId,type);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScreenshot>>> = ({ signal }) => getScreenshot(id,selectionId,type, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id && selectionId && type), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScreenshotQueryResult = NonNullable<Awaited<ReturnType<typeof getScreenshot>>>
export type GetScreenshotQueryError = GetScreenshot404


export function useGetScreenshot<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScreenshot>>,
          TError,
          Awaited<ReturnType<typeof getScreenshot>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScreenshot<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScreenshot>>,
          TError,
          Awaited<ReturnType<typeof getScreenshot>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScreenshot<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a screenshot
 */

export function useGetScreenshot<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScreenshotQueryOptions(id,selectionId,type,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetScreenshotSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScreenshotQueryKey(id,selectionId,type);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScreenshot>>> = ({ signal }) => getScreenshot(id,selectionId,type, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScreenshotSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getScreenshot>>>
export type GetScreenshotSuspenseQueryError = GetScreenshot404


export function useGetScreenshotSuspense<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScreenshotSuspense<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScreenshotSuspense<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a screenshot
 */

export function useGetScreenshotSuspense<TData = Awaited<ReturnType<typeof getScreenshot>>, TError = GetScreenshot404>(
 id: string,
    selectionId: string,
    type: 'full' | 'element', options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getScreenshot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScreenshotSuspenseQueryOptions(id,selectionId,type,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




