/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ListGroups200Item,
  PersistGroups200
} from '../../model';


export const getListGroupsResponseMock = (): ListGroups200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.number.float({fractionDigits: 2}), revealed: faker.datatype.boolean()})))

export const getPersistGroupsResponseMock = (overrideResponse: Partial<Extract<PersistGroups200, object>> = {}): PersistGroups200 => ({status: faker.helpers.arrayElement(['ok'] as const), ...overrideResponse})


export const getListGroupsMockHandler = (overrideResponse?: ListGroups200Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListGroups200Item[]> | ListGroups200Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/workspaces/:id/groups', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListGroupsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPersistGroupsMockHandler = (overrideResponse?: PersistGroups200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PersistGroups200> | PersistGroups200), options?: RequestHandlerOptions) => {
  return http.put('*/workspaces/:id/groups', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPersistGroupsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGroupsMock = () => [
  getListGroupsMockHandler(),
  getPersistGroupsMockHandler()
]
