/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListGroups200Item,
  PersistGroups200,
  PersistGroups400,
  PersistGroupsBodyItem
} from '../../model';





/**
 * @summary List all groups in a workspace
 */
export type listGroupsResponse200 = {
  data: ListGroups200Item[]
  status: 200
}

export type listGroupsResponseSuccess = (listGroupsResponse200) & {
  headers: Headers;
};
;

export type listGroupsResponse = (listGroupsResponseSuccess)

export const getListGroupsUrl = (id: string,) => {




  return `/workspaces/${id}/groups`
}

export const listGroups = async (id: string, options?: RequestInit): Promise<listGroupsResponse> => {

  const res = await fetch(getListGroupsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listGroupsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGroupsResponse
}





export const getListGroupsQueryKey = (id: string,) => {
    return [
    `/workspaces/${id}/groups`
    ] as const;
    }


export const getListGroupsQueryOptions = <TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) => listGroups(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>
export type ListGroupsQueryError = unknown


export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all groups in a workspace
 */

export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListGroupsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) => listGroups(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>
export type ListGroupsSuspenseQueryError = unknown


export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all groups in a workspace
 */

export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Replace all groups in a workspace
 */
export type persistGroupsResponse200 = {
  data: PersistGroups200
  status: 200
}

export type persistGroupsResponse400 = {
  data: PersistGroups400
  status: 400
}

export type persistGroupsResponseSuccess = (persistGroupsResponse200) & {
  headers: Headers;
};
export type persistGroupsResponseError = (persistGroupsResponse400) & {
  headers: Headers;
};

export type persistGroupsResponse = (persistGroupsResponseSuccess | persistGroupsResponseError)

export const getPersistGroupsUrl = (id: string,) => {




  return `/workspaces/${id}/groups`
}

export const persistGroups = async (id: string,
    persistGroupsBodyItem: PersistGroupsBodyItem[], options?: RequestInit): Promise<persistGroupsResponse> => {

  const res = await fetch(getPersistGroupsUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      persistGroupsBodyItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: persistGroupsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as persistGroupsResponse
}




export const getPersistGroupsMutationOptions = <TError = PersistGroups400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{id: string;data: PersistGroupsBodyItem[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{id: string;data: PersistGroupsBodyItem[]}, TContext> => {

const mutationKey = ['persistGroups'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof persistGroups>>, {id: string;data: PersistGroupsBodyItem[]}> = (props) => {
          const {id,data} = props ?? {};

          return  persistGroups(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PersistGroupsMutationResult = NonNullable<Awaited<ReturnType<typeof persistGroups>>>
    export type PersistGroupsMutationBody = PersistGroupsBodyItem[]
    export type PersistGroupsMutationError = PersistGroups400

    /**
 * @summary Replace all groups in a workspace
 */
export const usePersistGroups = <TError = PersistGroups400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{id: string;data: PersistGroupsBodyItem[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof persistGroups>>,
        TError,
        {id: string;data: PersistGroupsBodyItem[]},
        TContext
      > => {
      return useMutation(getPersistGroupsMutationOptions(options), queryClient);
    }
