/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  SelectionGroup,
  StatusResponse
} from '../../model';





/**
 * @summary List all groups in a workspace
 */
export type listGroupsResponse200 = {
  data: SelectionGroup[]
  status: 200
}

export type listGroupsResponseSuccess = (listGroupsResponse200) & {
  headers: Headers;
};
;

export type listGroupsResponse = (listGroupsResponseSuccess)

export const getListGroupsUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/groups`
}

export const listGroups = async (workspaceId: string, options?: RequestInit): Promise<listGroupsResponse> => {

  const res = await fetch(getListGroupsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listGroupsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGroupsResponse
}





export const getListGroupsQueryKey = (workspaceId: string,) => {
    return [
    `/workspaces/${workspaceId}/groups`
    ] as const;
    }


export const getListGroupsQueryOptions = <TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) => listGroups(workspaceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>
export type ListGroupsQueryError = unknown


export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all groups in a workspace
 */

export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListGroupsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(workspaceId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) => listGroups(workspaceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>
export type ListGroupsSuspenseQueryError = unknown


export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all groups in a workspace
 */

export function useListGroupsSuspense<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 workspaceId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsSuspenseQueryOptions(workspaceId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Replace all groups in a workspace
 */
export type persistGroupsResponse200 = {
  data: StatusResponse
  status: 200
}

export type persistGroupsResponseSuccess = (persistGroupsResponse200) & {
  headers: Headers;
};
;

export type persistGroupsResponse = (persistGroupsResponseSuccess)

export const getPersistGroupsUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/groups`
}

export const persistGroups = async (workspaceId: string,
    selectionGroup: SelectionGroup[], options?: RequestInit): Promise<persistGroupsResponse> => {

  const res = await fetch(getPersistGroupsUrl(workspaceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      selectionGroup,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: persistGroupsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as persistGroupsResponse
}




export const getPersistGroupsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{workspaceId: string;data: SelectionGroup[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{workspaceId: string;data: SelectionGroup[]}, TContext> => {

const mutationKey = ['persistGroups'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof persistGroups>>, {workspaceId: string;data: SelectionGroup[]}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  persistGroups(workspaceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PersistGroupsMutationResult = NonNullable<Awaited<ReturnType<typeof persistGroups>>>
    export type PersistGroupsMutationBody = SelectionGroup[]
    export type PersistGroupsMutationError = unknown

    /**
 * @summary Replace all groups in a workspace
 */
export const usePersistGroups = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistGroups>>, TError,{workspaceId: string;data: SelectionGroup[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof persistGroups>>,
        TError,
        {workspaceId: string;data: SelectionGroup[]},
        TContext
      > => {
      return useMutation(getPersistGroupsMutationOptions(options), queryClient);
    }
