/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  SelectionGroup,
  StatusResponse
} from '../../model';


export const getListGroupsResponseMock = (): SelectionGroup[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.number.float({fractionDigits: 2}), revealed: faker.datatype.boolean()})))

export const getPersistGroupsResponseMock = (overrideResponse: Partial<Extract<StatusResponse, object>> = {}): StatusResponse => ({status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ok'] as const), undefined]), ...overrideResponse})


export const getListGroupsMockHandler = (overrideResponse?: SelectionGroup[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SelectionGroup[]> | SelectionGroup[]), options?: RequestHandlerOptions) => {
  return http.get('*/workspaces/:workspaceId/groups', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListGroupsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPersistGroupsMockHandler = (overrideResponse?: StatusResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<StatusResponse> | StatusResponse), options?: RequestHandlerOptions) => {
  return http.put('*/workspaces/:workspaceId/groups', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPersistGroupsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGroupsMock = () => [
  getListGroupsMockHandler(),
  getPersistGroupsMockHandler()
]
