/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  HealthCheck200
} from '../../model';


export const getHealthCheckResponseMock = (overrideResponse: Partial<Extract<HealthCheck200, object>> = {}): HealthCheck200 => ({status: faker.helpers.arrayElement([faker.helpers.arrayElement(['ok'] as const), undefined]), ...overrideResponse})


export const getHealthCheckMockHandler = (overrideResponse?: HealthCheck200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<HealthCheck200> | HealthCheck200), options?: RequestHandlerOptions) => {
  return http.get('*/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getHealthCheckResponseMock(),
      { status: 200
      })
  }, options)
}
export const getHealthMock = () => [
  getHealthCheckMockHandler()
]
