/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListSelectionsParams,
  Selection,
  StatusResponse
} from '../../model';





/**
 * @summary List all selections in a workspace
 */
export type listSelectionsResponse200 = {
  data: Selection[]
  status: 200
}

export type listSelectionsResponseSuccess = (listSelectionsResponse200) & {
  headers: Headers;
};
;

export type listSelectionsResponse = (listSelectionsResponseSuccess)

export const getListSelectionsUrl = (workspaceId: string,
    params?: ListSelectionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workspaces/${workspaceId}/selections?${stringifiedParams}` : `/workspaces/${workspaceId}/selections`
}

export const listSelections = async (workspaceId: string,
    params?: ListSelectionsParams, options?: RequestInit): Promise<listSelectionsResponse> => {

  const res = await fetch(getListSelectionsUrl(workspaceId,params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSelectionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSelectionsResponse
}





export const getListSelectionsQueryKey = (workspaceId: string,
    params?: ListSelectionsParams,) => {
    return [
    `/workspaces/${workspaceId}/selections`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSelectionsQueryOptions = <TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSelectionsQueryKey(workspaceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSelections>>> = ({ signal }) => listSelections(workspaceId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSelectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSelections>>>
export type ListSelectionsQueryError = unknown


export function useListSelections<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params: undefined |  ListSelectionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSelections>>,
          TError,
          Awaited<ReturnType<typeof listSelections>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSelections<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSelections>>,
          TError,
          Awaited<ReturnType<typeof listSelections>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSelections<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all selections in a workspace
 */

export function useListSelections<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSelectionsQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListSelectionsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSelectionsQueryKey(workspaceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSelections>>> = ({ signal }) => listSelections(workspaceId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSelectionsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listSelections>>>
export type ListSelectionsSuspenseQueryError = unknown


export function useListSelectionsSuspense<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params: undefined |  ListSelectionsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSelectionsSuspense<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSelectionsSuspense<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all selections in a workspace
 */

export function useListSelectionsSuspense<TData = Awaited<ReturnType<typeof listSelections>>, TError = unknown>(
 workspaceId: string,
    params?: ListSelectionsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listSelections>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSelectionsSuspenseQueryOptions(workspaceId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Replace all selections in a workspace
 */
export type persistSelectionsResponse200 = {
  data: StatusResponse
  status: 200
}

export type persistSelectionsResponseSuccess = (persistSelectionsResponse200) & {
  headers: Headers;
};
;

export type persistSelectionsResponse = (persistSelectionsResponseSuccess)

export const getPersistSelectionsUrl = (workspaceId: string,) => {




  return `/workspaces/${workspaceId}/selections`
}

export const persistSelections = async (workspaceId: string,
    selection: Selection[], options?: RequestInit): Promise<persistSelectionsResponse> => {

  const res = await fetch(getPersistSelectionsUrl(workspaceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      selection,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: persistSelectionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as persistSelectionsResponse
}




export const getPersistSelectionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistSelections>>, TError,{workspaceId: string;data: Selection[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof persistSelections>>, TError,{workspaceId: string;data: Selection[]}, TContext> => {

const mutationKey = ['persistSelections'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof persistSelections>>, {workspaceId: string;data: Selection[]}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  persistSelections(workspaceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PersistSelectionsMutationResult = NonNullable<Awaited<ReturnType<typeof persistSelections>>>
    export type PersistSelectionsMutationBody = Selection[]
    export type PersistSelectionsMutationError = unknown

    /**
 * @summary Replace all selections in a workspace
 */
export const usePersistSelections = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistSelections>>, TError,{workspaceId: string;data: Selection[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof persistSelections>>,
        TError,
        {workspaceId: string;data: Selection[]},
        TContext
      > => {
      return useMutation(getPersistSelectionsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a single selection by ID
 */
export type getSelectionResponse200 = {
  data: Selection
  status: 200
}

export type getSelectionResponse404 = {
  data: void
  status: 404
}

export type getSelectionResponseSuccess = (getSelectionResponse200) & {
  headers: Headers;
};
export type getSelectionResponseError = (getSelectionResponse404) & {
  headers: Headers;
};

export type getSelectionResponse = (getSelectionResponseSuccess | getSelectionResponseError)

export const getGetSelectionUrl = (workspaceId: string,
    selectionId: string,) => {




  return `/workspaces/${workspaceId}/selections/${selectionId}`
}

export const getSelection = async (workspaceId: string,
    selectionId: string, options?: RequestInit): Promise<getSelectionResponse> => {

  const res = await fetch(getGetSelectionUrl(workspaceId,selectionId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSelectionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSelectionResponse
}





export const getGetSelectionQueryKey = (workspaceId: string,
    selectionId: string,) => {
    return [
    `/workspaces/${workspaceId}/selections/${selectionId}`
    ] as const;
    }


export const getGetSelectionQueryOptions = <TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSelectionQueryKey(workspaceId,selectionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSelection>>> = ({ signal }) => getSelection(workspaceId,selectionId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(workspaceId && selectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSelectionQueryResult = NonNullable<Awaited<ReturnType<typeof getSelection>>>
export type GetSelectionQueryError = void


export function useGetSelection<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSelection>>,
          TError,
          Awaited<ReturnType<typeof getSelection>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSelection<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSelection>>,
          TError,
          Awaited<ReturnType<typeof getSelection>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSelection<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single selection by ID
 */

export function useGetSelection<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSelectionQueryOptions(workspaceId,selectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetSelectionSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSelectionQueryKey(workspaceId,selectionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSelection>>> = ({ signal }) => getSelection(workspaceId,selectionId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSelectionSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getSelection>>>
export type GetSelectionSuspenseQueryError = void


export function useGetSelectionSuspense<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSelectionSuspense<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSelectionSuspense<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a single selection by ID
 */

export function useGetSelectionSuspense<TData = Awaited<ReturnType<typeof getSelection>>, TError = void>(
 workspaceId: string,
    selectionId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSelection>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSelectionSuspenseQueryOptions(workspaceId,selectionId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




