/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

export type HealthCheck200Status = typeof HealthCheck200Status[keyof typeof HealthCheck200Status];


export const HealthCheck200Status = {
  ok: 'ok',
} as const;
