/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthCheck200Status } from './healthCheck200Status';

export type HealthCheck200 = {
  status?: HealthCheck200Status;
};
