/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import type { ListComments200ItemStatus } from './listComments200ItemStatus';

export type ListComments200Item = {
  id: string;
  groupId: string;
  /** Element HTML snapshot */
  content: string;
  elementName: string;
  tagName: string;
  componentName?: string;
  elementsCount?: number;
  elementSelectors?: string[];
  commentText?: string;
  timestamp: number;
  revealed: boolean;
  /** Lifecycle status of a selection */
  status?: ListComments200ItemStatus;
  pageUrl?: string;
  pageTitle?: string;
  /** R2 key for full-page screenshot */
  screenshotFullPage?: string;
  /** R2 key for element screenshot */
  screenshotElement?: string;
  jiraTicketId?: string;
  capturedBy?: string;
};
