/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lifecycle status of a group
 */
export type ListGroups200ItemStatus = typeof ListGroups200ItemStatus[keyof typeof ListGroups200ItemStatus];


export const ListGroups200ItemStatus = {
  open: 'open',
  ticketed: 'ticketed',
  resolved: 'resolved',
} as const;
