/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lifecycle status of a selection
 */
export type ListComments200ItemStatus = typeof ListComments200ItemStatus[keyof typeof ListComments200ItemStatus];


export const ListComments200ItemStatus = {
  open: 'open',
  ticketed: 'ticketed',
  resolved: 'resolved',
} as const;
