/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import type { PersistComments200Status } from './persistComments200Status';

export type PersistComments200 = {
  status: PersistComments200Status;
};
