/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

export type PersistGroups200Status = typeof PersistGroups200Status[keyof typeof PersistGroups200Status];


export const PersistGroups200Status = {
  ok: 'ok',
} as const;
