/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import type { PersistGroups200Status } from './persistGroups200Status';

export type PersistGroups200 = {
  status: PersistGroups200Status;
};
