/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

export type PersistComments200Status = typeof PersistComments200Status[keyof typeof PersistComments200Status];


export const PersistComments200Status = {
  ok: 'ok',
} as const;
