/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lifecycle status of a group
 */
export type PersistGroupsBodyItemStatus = typeof PersistGroupsBodyItemStatus[keyof typeof PersistGroupsBodyItemStatus];


export const PersistGroupsBodyItemStatus = {
  open: 'open',
  ticketed: 'ticketed',
  resolved: 'resolved',
} as const;
