/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import type { SelectionStatus } from './selectionStatus';

export interface Selection {
  id: string;
  groupId: string;
  /** Element HTML snapshot */
  content: string;
  elementName: string;
  tagName: string;
  /** @nullable */
  componentName?: string | null;
  elementsCount?: number;
  elementSelectors?: string[];
  /** @nullable */
  commentText?: string | null;
  timestamp: number;
  revealed: boolean;
  status: SelectionStatus;
  /** @nullable */
  pageUrl?: string | null;
  /** @nullable */
  pageTitle?: string | null;
  /**
     * R2 key for full-page screenshot
     * @nullable
     */
  screenshotFullPage?: string | null;
  /**
     * R2 key for element screenshot
     * @nullable
     */
  screenshotElement?: string | null;
  /** @nullable */
  jiraTicketId?: string | null;
  /** @nullable */
  capturedBy?: string | null;
}
