/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

export type SelectionStatus = typeof SelectionStatus[keyof typeof SelectionStatus];


export const SelectionStatus = {
  open: 'open',
  ticketed: 'ticketed',
  resolved: 'resolved',
} as const;
