/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — selections, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */

export type StatusResponseStatus = typeof StatusResponseStatus[keyof typeof StatusResponseStatus];


export const StatusResponseStatus = {
  ok: 'ok',
} as const;
