/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CreateJiraTicket200,
  CreateJiraTicket400,
  CreateJiraTicketBody,
  GetJiraTicketStatus200,
  GetJiraTicketStatus404,
  ListJiraIssueTypes200Item,
  ListJiraPriorities200Item,
  ListJiraProjects200Item
} from '../../model';





/**
 * @summary Create a JIRA ticket from a group
 */
export type createJiraTicketResponse200 = {
  data: CreateJiraTicket200
  status: 200
}

export type createJiraTicketResponse400 = {
  data: CreateJiraTicket400
  status: 400
}

export type createJiraTicketResponseSuccess = (createJiraTicketResponse200) & {
  headers: Headers;
};
export type createJiraTicketResponseError = (createJiraTicketResponse400) & {
  headers: Headers;
};

export type createJiraTicketResponse = (createJiraTicketResponseSuccess | createJiraTicketResponseError)

export const getCreateJiraTicketUrl = (id: string,
    groupId: string,) => {




  return `/workspaces/${id}/groups/${groupId}/jira-ticket`
}

export const createJiraTicket = async (id: string,
    groupId: string,
    createJiraTicketBody: CreateJiraTicketBody, options?: RequestInit): Promise<createJiraTicketResponse> => {

  const res = await fetch(getCreateJiraTicketUrl(id,groupId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createJiraTicketBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createJiraTicketResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createJiraTicketResponse
}




export const getCreateJiraTicketMutationOptions = <TError = CreateJiraTicket400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJiraTicket>>, TError,{id: string;groupId: string;data: CreateJiraTicketBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createJiraTicket>>, TError,{id: string;groupId: string;data: CreateJiraTicketBody}, TContext> => {

const mutationKey = ['createJiraTicket'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJiraTicket>>, {id: string;groupId: string;data: CreateJiraTicketBody}> = (props) => {
          const {id,groupId,data} = props ?? {};

          return  createJiraTicket(id,groupId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateJiraTicketMutationResult = NonNullable<Awaited<ReturnType<typeof createJiraTicket>>>
    export type CreateJiraTicketMutationBody = CreateJiraTicketBody
    export type CreateJiraTicketMutationError = CreateJiraTicket400

    /**
 * @summary Create a JIRA ticket from a group
 */
export const useCreateJiraTicket = <TError = CreateJiraTicket400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJiraTicket>>, TError,{id: string;groupId: string;data: CreateJiraTicketBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createJiraTicket>>,
        TError,
        {id: string;groupId: string;data: CreateJiraTicketBody},
        TContext
      > => {
      return useMutation(getCreateJiraTicketMutationOptions(options), queryClient);
    }
    /**
 * @summary Get JIRA ticket status for a group
 */
export type getJiraTicketStatusResponse200 = {
  data: GetJiraTicketStatus200
  status: 200
}

export type getJiraTicketStatusResponse404 = {
  data: GetJiraTicketStatus404
  status: 404
}

export type getJiraTicketStatusResponseSuccess = (getJiraTicketStatusResponse200) & {
  headers: Headers;
};
export type getJiraTicketStatusResponseError = (getJiraTicketStatusResponse404) & {
  headers: Headers;
};

export type getJiraTicketStatusResponse = (getJiraTicketStatusResponseSuccess | getJiraTicketStatusResponseError)

export const getGetJiraTicketStatusUrl = (id: string,
    groupId: string,) => {




  return `/workspaces/${id}/groups/${groupId}/jira-status`
}

export const getJiraTicketStatus = async (id: string,
    groupId: string, options?: RequestInit): Promise<getJiraTicketStatusResponse> => {

  const res = await fetch(getGetJiraTicketStatusUrl(id,groupId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getJiraTicketStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getJiraTicketStatusResponse
}





export const getGetJiraTicketStatusQueryKey = (id: string,
    groupId: string,) => {
    return [
    `/workspaces/${id}/groups/${groupId}/jira-status`
    ] as const;
    }


export const getGetJiraTicketStatusQueryOptions = <TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(id: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJiraTicketStatusQueryKey(id,groupId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJiraTicketStatus>>> = ({ signal }) => getJiraTicketStatus(id,groupId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id && groupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJiraTicketStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getJiraTicketStatus>>>
export type GetJiraTicketStatusQueryError = GetJiraTicketStatus404


export function useGetJiraTicketStatus<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJiraTicketStatus>>,
          TError,
          Awaited<ReturnType<typeof getJiraTicketStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJiraTicketStatus<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJiraTicketStatus>>,
          TError,
          Awaited<ReturnType<typeof getJiraTicketStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJiraTicketStatus<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get JIRA ticket status for a group
 */

export function useGetJiraTicketStatus<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJiraTicketStatusQueryOptions(id,groupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetJiraTicketStatusSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(id: string,
    groupId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJiraTicketStatusQueryKey(id,groupId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJiraTicketStatus>>> = ({ signal }) => getJiraTicketStatus(id,groupId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJiraTicketStatusSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getJiraTicketStatus>>>
export type GetJiraTicketStatusSuspenseQueryError = GetJiraTicketStatus404


export function useGetJiraTicketStatusSuspense<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJiraTicketStatusSuspense<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJiraTicketStatusSuspense<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get JIRA ticket status for a group
 */

export function useGetJiraTicketStatusSuspense<TData = Awaited<ReturnType<typeof getJiraTicketStatus>>, TError = GetJiraTicketStatus404>(
 id: string,
    groupId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJiraTicketStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJiraTicketStatusSuspenseQueryOptions(id,groupId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List JIRA projects
 */
export type listJiraProjectsResponse200 = {
  data: ListJiraProjects200Item[]
  status: 200
}

export type listJiraProjectsResponseSuccess = (listJiraProjectsResponse200) & {
  headers: Headers;
};
;

export type listJiraProjectsResponse = (listJiraProjectsResponseSuccess)

export const getListJiraProjectsUrl = () => {




  return `/jira/projects`
}

export const listJiraProjects = async ( options?: RequestInit): Promise<listJiraProjectsResponse> => {

  const res = await fetch(getListJiraProjectsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listJiraProjectsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listJiraProjectsResponse
}





export const getListJiraProjectsQueryKey = () => {
    return [
    `/jira/projects`
    ] as const;
    }


export const getListJiraProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraProjectsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraProjects>>> = ({ signal }) => listJiraProjects({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraProjects>>>
export type ListJiraProjectsQueryError = unknown


export function useListJiraProjects<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraProjects>>,
          TError,
          Awaited<ReturnType<typeof listJiraProjects>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraProjects<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraProjects>>,
          TError,
          Awaited<ReturnType<typeof listJiraProjects>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraProjects<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA projects
 */

export function useListJiraProjects<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListJiraProjectsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraProjectsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraProjects>>> = ({ signal }) => listJiraProjects({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraProjectsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraProjects>>>
export type ListJiraProjectsSuspenseQueryError = unknown


export function useListJiraProjectsSuspense<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraProjectsSuspense<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraProjectsSuspense<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA projects
 */

export function useListJiraProjectsSuspense<TData = Awaited<ReturnType<typeof listJiraProjects>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraProjectsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List JIRA issue types
 */
export type listJiraIssueTypesResponse200 = {
  data: ListJiraIssueTypes200Item[]
  status: 200
}

export type listJiraIssueTypesResponseSuccess = (listJiraIssueTypesResponse200) & {
  headers: Headers;
};
;

export type listJiraIssueTypesResponse = (listJiraIssueTypesResponseSuccess)

export const getListJiraIssueTypesUrl = () => {




  return `/jira/issue-types`
}

export const listJiraIssueTypes = async ( options?: RequestInit): Promise<listJiraIssueTypesResponse> => {

  const res = await fetch(getListJiraIssueTypesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listJiraIssueTypesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listJiraIssueTypesResponse
}





export const getListJiraIssueTypesQueryKey = () => {
    return [
    `/jira/issue-types`
    ] as const;
    }


export const getListJiraIssueTypesQueryOptions = <TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraIssueTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraIssueTypes>>> = ({ signal }) => listJiraIssueTypes({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraIssueTypesQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraIssueTypes>>>
export type ListJiraIssueTypesQueryError = unknown


export function useListJiraIssueTypes<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraIssueTypes>>,
          TError,
          Awaited<ReturnType<typeof listJiraIssueTypes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraIssueTypes<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraIssueTypes>>,
          TError,
          Awaited<ReturnType<typeof listJiraIssueTypes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraIssueTypes<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA issue types
 */

export function useListJiraIssueTypes<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraIssueTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListJiraIssueTypesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraIssueTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraIssueTypes>>> = ({ signal }) => listJiraIssueTypes({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraIssueTypesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraIssueTypes>>>
export type ListJiraIssueTypesSuspenseQueryError = unknown


export function useListJiraIssueTypesSuspense<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraIssueTypesSuspense<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraIssueTypesSuspense<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA issue types
 */

export function useListJiraIssueTypesSuspense<TData = Awaited<ReturnType<typeof listJiraIssueTypes>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraIssueTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraIssueTypesSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List JIRA priorities
 */
export type listJiraPrioritiesResponse200 = {
  data: ListJiraPriorities200Item[]
  status: 200
}

export type listJiraPrioritiesResponseSuccess = (listJiraPrioritiesResponse200) & {
  headers: Headers;
};
;

export type listJiraPrioritiesResponse = (listJiraPrioritiesResponseSuccess)

export const getListJiraPrioritiesUrl = () => {




  return `/jira/priorities`
}

export const listJiraPriorities = async ( options?: RequestInit): Promise<listJiraPrioritiesResponse> => {

  const res = await fetch(getListJiraPrioritiesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listJiraPrioritiesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listJiraPrioritiesResponse
}





export const getListJiraPrioritiesQueryKey = () => {
    return [
    `/jira/priorities`
    ] as const;
    }


export const getListJiraPrioritiesQueryOptions = <TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraPrioritiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraPriorities>>> = ({ signal }) => listJiraPriorities({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraPrioritiesQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraPriorities>>>
export type ListJiraPrioritiesQueryError = unknown


export function useListJiraPriorities<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraPriorities>>,
          TError,
          Awaited<ReturnType<typeof listJiraPriorities>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraPriorities<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listJiraPriorities>>,
          TError,
          Awaited<ReturnType<typeof listJiraPriorities>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraPriorities<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA priorities
 */

export function useListJiraPriorities<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraPrioritiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListJiraPrioritiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJiraPrioritiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJiraPriorities>>> = ({ signal }) => listJiraPriorities({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListJiraPrioritiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listJiraPriorities>>>
export type ListJiraPrioritiesSuspenseQueryError = unknown


export function useListJiraPrioritiesSuspense<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraPrioritiesSuspense<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListJiraPrioritiesSuspense<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List JIRA priorities
 */

export function useListJiraPrioritiesSuspense<TData = Awaited<ReturnType<typeof listJiraPriorities>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listJiraPriorities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListJiraPrioritiesSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




