/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateJiraTicket200,
  GetJiraTicketStatus200,
  ListJiraIssueTypes200Item,
  ListJiraPriorities200Item,
  ListJiraProjects200Item
} from '../../model';


export const getCreateJiraTicketResponseMock = (overrideResponse: Partial<Extract<CreateJiraTicket200, object>> = {}): CreateJiraTicket200 => ({jiraTicketId: faker.string.alpha({length: {min: 10, max: 20}}), jiraUrl: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetJiraTicketStatusResponseMock = (overrideResponse: Partial<Extract<GetJiraTicketStatus200, object>> = {}): GetJiraTicketStatus200 => ({status: faker.string.alpha({length: {min: 10, max: 20}}), statusCategory: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getListJiraProjectsResponseMock = (): ListJiraProjects200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({key: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getListJiraIssueTypesResponseMock = (): ListJiraIssueTypes200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getListJiraPrioritiesResponseMock = (): ListJiraPriorities200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}})})))


export const getCreateJiraTicketMockHandler = (overrideResponse?: CreateJiraTicket200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateJiraTicket200> | CreateJiraTicket200), options?: RequestHandlerOptions) => {
  return http.post('*/workspaces/:id/groups/:groupId/jira-ticket', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateJiraTicketResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetJiraTicketStatusMockHandler = (overrideResponse?: GetJiraTicketStatus200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetJiraTicketStatus200> | GetJiraTicketStatus200), options?: RequestHandlerOptions) => {
  return http.get('*/workspaces/:id/groups/:groupId/jira-status', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetJiraTicketStatusResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListJiraProjectsMockHandler = (overrideResponse?: ListJiraProjects200Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListJiraProjects200Item[]> | ListJiraProjects200Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/jira/projects', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListJiraProjectsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListJiraIssueTypesMockHandler = (overrideResponse?: ListJiraIssueTypes200Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListJiraIssueTypes200Item[]> | ListJiraIssueTypes200Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/jira/issue-types', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListJiraIssueTypesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListJiraPrioritiesMockHandler = (overrideResponse?: ListJiraPriorities200Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListJiraPriorities200Item[]> | ListJiraPriorities200Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/jira/priorities', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListJiraPrioritiesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getJiraMock = () => [
  getCreateJiraTicketMockHandler(),
  getGetJiraTicketStatusMockHandler(),
  getListJiraProjectsMockHandler(),
  getListJiraIssueTypesMockHandler(),
  getListJiraPrioritiesMockHandler()
]
