/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ListComments200Item,
  PersistComments200
} from '../../model';


export const getListCommentsResponseMock = (): ListComments200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), groupId: faker.string.alpha({length: {min: 10, max: 20}}), content: faker.string.alpha({length: {min: 10, max: 20}}), elementName: faker.string.alpha({length: {min: 10, max: 20}}), tagName: faker.string.alpha({length: {min: 10, max: 20}}), componentName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), elementsCount: faker.helpers.arrayElement([faker.number.int(), undefined]), elementSelectors: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), commentText: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), timestamp: faker.number.float({fractionDigits: 2}), revealed: faker.datatype.boolean(), status: faker.helpers.arrayElement([faker.helpers.arrayElement(['open','ticketed','resolved'] as const), undefined]), pageUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), pageTitle: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), screenshotFullPage: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), screenshotElement: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), jiraTicketId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), capturedBy: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})))

export const getPersistCommentsResponseMock = (overrideResponse: Partial<Extract<PersistComments200, object>> = {}): PersistComments200 => ({status: faker.helpers.arrayElement(['ok'] as const), ...overrideResponse})


export const getListCommentsMockHandler = (overrideResponse?: ListComments200Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListComments200Item[]> | ListComments200Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/workspaces/:id/comments', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListCommentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPersistCommentsMockHandler = (overrideResponse?: PersistComments200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PersistComments200> | PersistComments200), options?: RequestHandlerOptions) => {
  return http.put('*/workspaces/:id/comments', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPersistCommentsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getCommentsMock = () => [
  getListCommentsMockHandler(),
  getPersistCommentsMockHandler()
]
