/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * react-grab Sync API
 * API for the react-grab dashboard — comments, groups, workspaces.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ListComments200Item,
  PersistComments200,
  PersistComments400,
  PersistCommentsBodyItem
} from '../../model';





/**
 * @summary List all comments in a workspace
 */
export type listCommentsResponse200 = {
  data: ListComments200Item[]
  status: 200
}

export type listCommentsResponseSuccess = (listCommentsResponse200) & {
  headers: Headers;
};
;

export type listCommentsResponse = (listCommentsResponseSuccess)

export const getListCommentsUrl = (id: string,) => {




  return `/workspaces/${id}/comments`
}

export const listComments = async (id: string, options?: RequestInit): Promise<listCommentsResponse> => {

  const res = await fetch(getListCommentsUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listCommentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listCommentsResponse
}





export const getListCommentsQueryKey = (id: string,) => {
    return [
    `/workspaces/${id}/comments`
    ] as const;
    }


export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = unknown


export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listComments>>,
          TError,
          Awaited<ReturnType<typeof listComments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listComments>>,
          TError,
          Awaited<ReturnType<typeof listComments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all comments in a workspace
 */

export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCommentsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListCommentsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsSuspenseQueryError = unknown


export function useListCommentsSuspense<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsSuspense<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsSuspense<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all comments in a workspace
 */

export function useListCommentsSuspense<TData = Awaited<ReturnType<typeof listComments>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCommentsSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Replace all comments in a workspace
 */
export type persistCommentsResponse200 = {
  data: PersistComments200
  status: 200
}

export type persistCommentsResponse400 = {
  data: PersistComments400
  status: 400
}

export type persistCommentsResponseSuccess = (persistCommentsResponse200) & {
  headers: Headers;
};
export type persistCommentsResponseError = (persistCommentsResponse400) & {
  headers: Headers;
};

export type persistCommentsResponse = (persistCommentsResponseSuccess | persistCommentsResponseError)

export const getPersistCommentsUrl = (id: string,) => {




  return `/workspaces/${id}/comments`
}

export const persistComments = async (id: string,
    persistCommentsBodyItem: PersistCommentsBodyItem[], options?: RequestInit): Promise<persistCommentsResponse> => {

  const res = await fetch(getPersistCommentsUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      persistCommentsBodyItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: persistCommentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as persistCommentsResponse
}




export const getPersistCommentsMutationOptions = <TError = PersistComments400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistComments>>, TError,{id: string;data: PersistCommentsBodyItem[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof persistComments>>, TError,{id: string;data: PersistCommentsBodyItem[]}, TContext> => {

const mutationKey = ['persistComments'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof persistComments>>, {id: string;data: PersistCommentsBodyItem[]}> = (props) => {
          const {id,data} = props ?? {};

          return  persistComments(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PersistCommentsMutationResult = NonNullable<Awaited<ReturnType<typeof persistComments>>>
    export type PersistCommentsMutationBody = PersistCommentsBodyItem[]
    export type PersistCommentsMutationError = PersistComments400

    /**
 * @summary Replace all comments in a workspace
 */
export const usePersistComments = <TError = PersistComments400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof persistComments>>, TError,{id: string;data: PersistCommentsBodyItem[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof persistComments>>,
        TError,
        {id: string;data: PersistCommentsBodyItem[]},
        TContext
      > => {
      return useMutation(getPersistCommentsMutationOptions(options), queryClient);
    }
